theme: jekyll-theme-midnight
title: Woodlands Help
subtitle:
navigation: 1
sections: [
  ['locations', 'Village Square'],
  ['/', 'Things to Do']
]
url: https://dagwud.github.io/
baseurl: /thewoodlands-help
